### ISSUE TITLE
Install script fails on future3

### ISSUE THREAD

**Issue by chrisih** [MiczFlor/RPi-Jukebox-RFID#1585]
### Problem 

Install script does not work. Some stuff seems to be downloaded, but after some seconds all is over...
Setup was done on a fresh Raspbian (raspios-buster) via SSH.
Seems the script on the WebPage (https://rpi-jukebox-rfid.readthedocs.io/en/latest/install.html#initial-boot) uses this script: cd; bash <(wget -qO- https://raw.githubusercontent.com/MiczFlor/RPi-Jukebox-RFID/future3/develop/installation/install-jukebox.sh)
Using instead the one from future3/main seems to work, so maybe the command line on the install page should point to future3/main instead of future3/develop.

#### What's your hardware set up? 

RPI 3B+, USB-connected RFID reader

#### If possible, try to attach logs from ... (paths from RPi)

Log start: 1634735966
Download Source: https://github.com/MiczFlor/RPi-Jukebox-RFID/future3/main
/dev/fd/63: line 57: /home/pi/RPi-Jukebox-RFID/installation/includes/*: No such file or directory
/dev/fd/63: line 61: /home/pi/RPi-Jukebox-RFID/installation/routines/*: No such file or directory
/dev/fd/63: line 64: welcome: command not found
/dev/fd/63: line 65: run_with_timer: command not found
/dev/fd/63: line 66: finish: command not found

**Comment by pabera** [comment]
Thanks for checking out the `future3/main` branch. Your help is very much appreciated. Ever since we have launched the first Alpha version, lots of changes have happened. And that work can be found on `future3/develop`.

In fact, it makes sense to use this branch and test again. Let us know if you face any trouble. A few steps have to be done to achieve this. 

---

1. Start with a fresh Raspi OS image and ssh into your Pi.
2. Download the latest install script like this

```
$ wget https://raw.githubusercontent.com/MiczFlor/RPi-Jukebox-RFID/future3/develop/installation/install-jukebox.sh
```

3. Edit the downloaded file with your preferred editor, e.g. `nano`.

```
$ nano install-jukebox.sh
```

4. Amed [Line 8](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/future3/develop/installation/install-jukebox.sh#L8) like this

```
GIT_BRANCH="future3/develop"
```

5. Save the file, make it executable and run it with the following commands.

```
$ chmod +x install-jukebox.sh
$ ./install-jukebox.sh
```

**Comment by teute03** [comment]
Hi, I am using the version 2 since almost two year now without any major issue and I am planning to build a new one and was pleased to see all the work done. Many thanks !

I did a fresh install on a Rpi3, with activation of webapp and kiosk mode on the `future3/develop` branch as per your comment.
I get a message `403 forbidden` when trying to connect with a internet browser to RPI adresse, and the screen attached to the RPI also show a page with the 403 forbidden.

I did a `chmod +x` on the main folder (not sure if this has done something) and run the script `RPi-Jukebox-RFID/src/webapp/run_rebuild.sh` and it correct it.
I see that a pull request is ongoing with some change in installation files, so maybe this is already addressed.
