### ISSUE TITLE
Phoniebox with Logitech V20 Speaker

### ISSUE THREAD

**Issue by ekorn** [MiczFlor/RPi-Jukebox-RFID#164]
More a recommendation than an issue. I used second hand Logitech V20 Speaker. They have some keys and will be recognized as normal usb keyboard input. So I made this file:
```
#play/pause
string F100 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerpause\n"
string F101 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerstop\n"
string F102 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerprev\n"
string F103 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playernext\n"
#mute/unmute
string F104 = "amixer -c 1 set PCM 1+ toggle\n"
string F105 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=volumeup\n"
string F106 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=volumedown\n"

keycode 164 = F100
keycode 166 = F101
keycode 165 = F102
keycode 163 = F103
keycode 113 = F104
keycode 115 = F105
keycode 114 = F106
```
store it here 

`/home/pi/RPi-Jukebox-RFID/misc/mykeys`

And test the file with Phoniebox keybindings for the Logitech V20 Speaker with
`loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys`
for that test I logged in not via ssh but local with a Keyboard an a monitor on a text console not a graphical (X) one. 
Finally after I make sure that it worked I add the loadkeys command to the end of  the /etc/rc.local above the last line of code (exit 0 ) to autostart it. 
Also and make sure that the pi user is logged in so that the key inputs work with raspi-config->Boot Options->Autologin Text Console

**Comment by SKHSKHilber** [comment]
Thank you for this. Because this seems like such a great way to connect buttons without any soldering, I got v20s second hand. 

Unfortunately I don't get the buttons to work. The music plays well and when I change the sound source in the desktop to usb speakers, I can change the volume and mute, but the 4 other buttons don't work.
It seems very straight forward, so I don't understand my mistake?!
Maybe the two following questions will clear it up:
What does "and add it to the end of" mean? the very end or possibly before the "exit 0"?
Also: I assume I am logged in as pi. I am when it says pi@raspberry in the terminal, right?

**Comment by ekorn** [comment]
You have to put it  above the last line of code (exit 0 ) and the auto login is for a local session nat a ssh session to test it connect a keyboard an a monitor boot it up. When autologn works you login in as the user pi and when you push a button on the V20 it will be exactly like typing that command in.

**Comment by SKHSKHilber** [comment]
Hi @ekorn, thank you so much for your help. Unfortunately it's still not working.

This is the full content of my  /etc/rc.local file. Do you see the problem, by any chance?

`#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

#File with Phoniebox keybindings for the Logitech V20 Speaker
#loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys

#play/pause
string F100 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerpause\n"
string F101 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerstop\n"
string F102 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playerprev\n"
string F103 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=playernext\n"
#mute/unmute
string F104 = "amixer -c 1 set PCM 1+ toggle\n"
string F105 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=volumeup\n"
string F106 = "/home/pi/RPi-Jukebox-RFID/scripts/playout_controls.sh -c=volumedown\n"

keycode 164 = F100
keycode 166 = F101
keycode 165 = F102
keycode 163 = F103
keycode 113 = F104
keycode 115 = F105
keycode 114 = F106

exit 0`

**Comment by ekorn** [comment]
Yes see your problem I updated my initial post from August 2018 to make it clearer I hope it helps

**Comment by SKHSKHilber** [comment]
Still not working. 
Here is what I did: sudo nano /home/pi/RPi-Jukebox-RFID/misc/mykeys
Then copied your code into this new file and saved it.
Then sudo /home/pi/RPi-Jukebox-RFID/misc/mykeys    to load it 
Then tried the buttons without any result
The /etc/rc.local I changed to the following:

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

#File with Phoniebox keybindings for the Logitech V20 Speaker
loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys
exit 0

Is that what you meant? Also after reboot it is not working...

**Comment by ekorn** [comment]
do you attached a keyboard and a monitor ? do you logged in locally ?
you can test it with `loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys`
`loadkeys` is the program `/home/pi/RPi-Jukebox-RFID/misc/mykeys` is the config file for loadkeys program.  If it does not work while testing it will not work in the /etc/rc.local either. Apart from this advice it looks good.

**Comment by SKHSKHilber** [comment]
I have attached a keyboard and a touchmonitor. I'm not sure what it means "to be logged in locally". When I boot I arrive at the desktop. 
"loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys" creates an error message:
"Dateideskriptor, auf den die Konsole verweist, konnte nicht gefunden werden."

sudo /home/pi/RPi-Jukebox-RFID/misc/mykeys 
"Befehl nicht gefunden"

sudo loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys does not do anything visible

The word "loadkeys" does not appear in the code that is stored in the file /home/pi/RPi-Jukebox-RFID/misc/mykeys isn't that a problem?

**Comment by ekorn** [comment]
ok for that test you should logged in not via ssh but local with a Keyboard an a monitor on a **text console** not a graphical (X) one. For that type STRG+ALT+ F2 and the try `loadkeys /home/pi/RPi-Jukebox-RFID/misc/mykeys` then try the buttons on the V20

**Comment by SKHSKHilber** [comment]
Yes that's it. CTRL+ALT+F2 did the trick! Thank you!
So I understand that I need to just boot to the text console for it to work. The desktop will never work, right?

**Comment by ekorn** [comment]
Yes just check what I wrote in the last line

> Also and make sure that the pi user is logged in so that the key inputs work with raspi-config->Boot Options->Autologin Text Console

This way it should not boot to the desktop (which you don't need anyway it will just suck resources )

**Comment by SKHSKHilber** [comment]
Will do, thank you very much!
