### ISSUE TITLE
🚀One Button for Next Song and Skip Forward

### ISSUE THREAD

**Issue by Nacktmull87** [MiczFlor/RPi-Jukebox-RFID#1666]
Hi everyone,

is it possible to give one Button  two functions of Play Next Song when Pushed The Button for a short Time and skip Forward when its hold for a View Seconds?

I tried IT, but when i hold The Button its jumping to the Next Song and then IT Starts to skip in the song. Is there Any Chance that this will not Happen? 

I Hope you will understand what i mean.

Thx for your help.

Sry for my Bad english

**Comment by TheDuffman85** [comment]
Only thing that worked for me is to reverse the order. Forward seek on short push and next title on long push. If you long push the button first it will perform a forward seek and then skip to the next title.

**Comment by AlvinSchiller** [comment]
Referenced Tickets:
https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1999
https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2247
https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2365


https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/1827

**Comment by AlvinSchiller** [comment]
This is now fixed with #https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2367 in v2.8.0.
The behavior of `hold_mode` `SecondFunc` and `SecondFuncRepeat` has changed. The secondary function is no longer triggered additionally to the primary function.
Now its called exclusively if `hold_time` is reached. The primary function will only be triggered if the button is pressed shorter then `hold_time`! Existing configurations may need to adapt to this.
