### ISSUE TITLE
jukebox-daemon.service as non root service

### ISSUE THREAD

**Issue by ThomasRausU** [MiczFlor/RPi-Jukebox-RFID#1708]
At least in my setup (yocto) it's not possible to access user-mode PulseAudio (mixer controls) by jukebox-daemon when running as root.
I wonder if you discussed about running jukebox-daemon as non root in user-mode. Of course hardware (spi, gpio) access must be granted via user groups (spi, gpio). [e.g. like this or raspian style](https://forum.up-community.org/discussion/2141/solved-tutorial-gpio-i2c-spi-access-without-root-permissions)

**Comment by ChisSoc** [comment]
Since Version 3.1.0, the Jukebox Service runs as user pi (in user mode) to connect to PulseAudio (same as MPD). Which version of future3 are you running? (Note: prior to  3.1.0 we did not use PulseAudio).

On my machine the service runs under user pi:
~~~
ps -elf | grep jukebox
0 S pi         685   603 15  80   0 - 94639 poll_s 17:09 ?        00:00:04 /usr/bin/python3 run_jukebox.py
~~~

**Comment by ThomasRausU** [comment]
you named it. I installed this in the system mode directory and not user mode as you do with the current install script (since I can not use it with Yocto).
Now everything is running in user mode and my suggested changes are obsolete (beside nanoseconds).
thank you!

**Comment by ChisSoc** [comment]
Great! You might find [this part of the Docs helpful](https://rpi-jukebox-rfid.readthedocs.io/en/latest/userguide/system.html)
