### ISSUE TITLE
🚀 | "next_song" performing no action when no next song is available

### ISSUE THREAD

**Issue by IgorWalton** [MiczFlor/RPi-Jukebox-RFID#2327]
### Feature

I would like the next_song GPIO button to do nothing, when there is no next song available (last track of a folder or single track without any folder). Currently this will stop the playback.

### User perspective

I imagine my (very young) child will pretty randomly press all of the available buttons, so this behaviour would be better suited.

### Further information

using Jukebox Core Version 3.5.2

**Comment by Lippsson** [comment]
Good feature request. It would be great if that above is the standard behavior

**Comment by pabera** [comment]
I think this is what the following PR is trying to solve?!

* #2326

**Comment by hoffie** [comment]
Hrm, the linked PR will behave in the following way:
1. When the last song of a playlist is being played and next() is called, the default will be to stop playing (this is configurable).
1. When the player is stopped (e.g. because the last song of a playlist finished) and the next() is called, the player will rewind the playlist (i.e. it will start playing the first song of the playlist again).

@IgorWalton Is that what you're after? If not, we would have to make (2) configurable as well.

**Comment by IgorWalton** [comment]
1. I personally would prefer if the default is "no action" in this situation
2. The way I think would make the most sense is during a stop in the middle of a track "next" jumps to the next track in the current playlist, and at the end of a playlist it there's either "no action" or "start playing the first song of the playlist"
I don't have the developer perspective (yet), so just 2 Cents from a User's perspective...

**Comment by hoffie** [comment]
As #2326 seems to be merged soonish, I can prepare another PR to add the *no action* behavior for (1).
Regarding (2), this can certainly be implemented as well. I was a bit hesitant to make this configurable, because every option adds code and config complexity, but I guess it's worth it if there are people who want to use it like that. :)

**Comment by s-martin** [comment]
You can still add it, if you want

**Comment by hoffie** [comment]
> I personally would prefer if the default is "no action" in this situation

#2326 should now technically cover this.


> The way I think would make the most sense is during a stop in the middle of a track "next" jumps to the next track in the current playlist

Done.

> at the end of a playlist it there's either "no action" or "start playing the first song of the playlist"

This should now behave similar to the case when running `next()` while playling the last song of the playlist (= it's configurable).

**Comment by s-martin** [comment]
#2326 has been merged to future3/develop
