### ISSUE TITLE
Please build stable version

### ISSUE THREAD

**Issue by TKlement** [MiczFlor/RPi-Jukebox-RFID#342]
I have the greatest respect for this project so don't get the wrong idea but please stop adding features and build one stable version.

I'm trying for days to get this running and have to go up and down all issues to find every little bug fix to get to the next step.
My setup is working with:
- Raspberry Pi 2
- RFID-RC522
- Stretch
- Headphone, no USB Audio stick at the moment

The current master branch is not working. There is no device found.
The only branch I found is Version-1.1.5-dynamicRFIDreader.
I had to struggle with playlist m3u problems after uploading a mp3.
It always wants to load a playlist from /tmp and returned with a mpd error.
I fixed it and in the end no errors but when I swipped a card there is no music.
So far I will give up and try it maybe later.

When I compare master with that branch it looks like that these changes are not included. Why?

**Comment by TKlement** [comment]
Ok, now I'm back to v1.1.7 and I can play my music in the web app.
But on this branch I'm unable to find my RFID-RC522 device. So I can not trigger it with my rfid card.
When I run RegisterDevice.py there is no device listed.

**Comment by MaxZimmermann99** [comment]
I feel you, i had the same trouble the last 3 weeks. I decided to step back and wait for some days before starting again. 
I use a Raspberry Zero with a RaspiAudioZero Soundcard. Stretch, Rotary knob and a RC522 RFID Reader. I got it all working somehow but never in a stable way and only with taking scripts from several Issues (like you said). 

I think there is a lot of stuff going on in the Background, the new wiki, so many new Features, Spotify... 
I hope it's gonna be better and easier in a few weeks :) 
I love the Project and i love all the guys doing this in their free time. And i already learned a lot about Linux and python! So dont get me wrong and keep on doing the great work! I'm just gonna wait a bit and start again!

**Comment by MiczFlor** [comment]
Hi @TKlement @MaxZimmermann99 
I feel you, too :) as the owner of the project, I have partly made it grow in features (based on great ideas in the community, thanks!) and seen it grow (based on code contributions, which elevated the scope, thanks!). @MaxZimmermann99 is a good example why it has become more complex to install: "Raspberry Zero with a RaspiAudioZero Soundcard, Stretch, Rotary knob and a RC522 RFID Reader"

When I started the project, the idea was very "Apple" if you like: you know the hardware and it's all plug and play, using RFID cards as the only UI. Then I added the web app to control the playout. Then the suggestion came to use the web app also for adding files and changing the configuration (which was and is a good idea and I integrated that), then more hardware was thrown in the ring and the soldering irons came out to play with GPIO buttons and dials. All good stuff - and suddenly also more complex to maintain. And test.

Often it's the case that new code contributions work for one setup and once they are out in the wild, they create problems for different hardware and bug fixes create problems for custom setups (audio on USB or external hard disk for example). 

I have been thinking about how to best handle this process, the balance of "growth versus stability". Spotify is a good example, many people really, really wanted this. And it's there, thanks to @princemaxwell. Then it did create problems once it was public, the fixes required upgrades and the documentation lacked behind. So it is wonderful to have it, but as a distributed project, this also meant that there is nobody who tests everything on all possibly hardware (which would be quite a task, given the different non-USB RFID readers currently used in the Phoniebox community).

@princemaxwell and I decided to have two "versions", the *classic* and the *+spotify* (where the `+` already indicates that I am sure more will come). 

My goal would be to work on the *classic* documentation and installation and make this stable. That's what I can do (and will do as soon as my new job gives me a bit more elbow room :) 

In my mind everything else is "experimental" and that's why I started the wiki: to give more spaces for code snippets regarding special hardware and hacked features. 

I am writing this not in defense, but to explain where the project stands and also to indicate that I am still following the discussion and hope to jump back in the ring to clean up soon. This thread is valuable, because it allows me to do this. And I am happy that a) you feel strongly and positive about the Phoniebox project and b) you understand that the culture of this project is capable of such critique and input. Which it is. Thanks for that.

All the best, micz

**Comment by marcohorstmann** [comment]
Ahhh this explains why nearly 2 weeks nothing didn't happen to my pull request ;)
Congratulations to your new job.

**Comment by gizmo21** [comment]
I have also trouble with 1.1.8-rc2 classic coming from 1.0.0 - my RFID Reader does accept the second swipe option play/pause once (second swipe) but does ignore it on forth swipe or 6th swipe. 
So after 3 swipes the swipes are ignored and the folder keeps playing.

I would like to switch to a v1.1.1 or v1.1.6. version (https://github.com/MiczFlor/RPi-Jukebox-RFID/releases/tag/v1.1.6)  like described in the upgrade manual, but I can't get the right commands to switch back to, anyone?

**Comment by thade666** [comment]
Same problem here. Pi2 with RC522. I tried out every "workaround" but i can't get it working together.

**Comment by MiczFlor** [comment]
Hi @thade666 @gizmo21 
Please have a read here
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/RFID-Reader-Special
Because the last attempt to unify all efid readers in one script created mayhem for many usb reader users, I split the scripts to stable and experimental. Usb readers are the majority and in the spirit of this thread (make stable olease) I decided for this split. 
All the best, micz
