### ISSUE TITLE
using mpd

### ISSUE THREAD

**Issue by kle99** [MiczFlor/RPi-Jukebox-RFID#356]
1.) In your FAQ [Audio is not working](https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/MANUAL#audio-is-not-working) you recommend to modify file `/usr/share/alsa/alsa.conf`
Well that works but the better way is to add or modify file `/etc/asound.conf`

```
sudo nano /etc/asound.conf
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}
```
2.) One question at last: you modified `/etc/mpd.conf` to run mpd as root user despite the warning. What is the reason?

**Comment by MiczFlor** [comment]
Hi @kle99 
Thanks for your contribution. I added your suggestion, linking to this post, because I could not test it:
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/MANUAL#audio-is-not-working

and (2): well, this comes from a time where the playlists were added in the /tmp directory and mpd didn't do that without being root. Not sure what would break if that was changed :) even though the playlists are now stored elsewhere. Wanna give it a try? :)
