### ISSUE TITLE
Recommended misc/sampleconfigs/gpio-buttons.py.sample changes

### ISSUE THREAD

**Issue by linusg** [MiczFlor/RPi-Jukebox-RFID#394]
A [user](https://forum-raspberrypi.de/user/36638-hyle/) from forum-raspberrypi.de asked me to bring these to your attention, and I belive he's absolutely right. The [file in question](https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/misc/sampleconfigs/gpio-buttons.py.sample) was originally submitted by @marcohorstmann and was taken from [a post in said forum](https://forum-raspberrypi.de/forum/thread/13144-projekt-jukebox4kids-jukebox-fuer-kinder/?postID=312257#post312257).

- Using (computed) absolute paths should be preferred at all times. This is not the case in the script, and while the current working directory might be set to the root to the repository in most cases, the script should not depend on it IMHO!
- The lines 22-41 heavily break the DRY rule, this could be fixed in the same commit
- All occurrences of `pull_up=True` can be removed, this is the default anyway: https://gpiozero.readthedocs.io/en/stable/api_input.html#gpiozero.Button

**Comment by MiczFlor** [comment]
Hi @linusg 
thanks for the contribution. It seems that I really need to get my soldering iron out and work with GPIO buttons. Many discussions I can only read and not try - because I do not use GPIO and rely on reports and other contributors' tests.
Could you create a pull request to discuss the changes with others?
All the best, micz
