### ISSUE TITLE
Web UI XHR (XML Http Requests)

### ISSUE THREAD

**Issue by comdoxx** [MiczFlor/RPi-Jukebox-RFID#446]
Hi Micz.

as I am playing more and more with the frontend, I find it more and more annoying that the whole page reloads, when links such as "Toggle Resume" is pressed. I found that some things are already ajax-driven, but that seems to be a one way street: Covers, Info, Time, etc. change according to their specific triggers, but clicking "Play" will reload the page instead of just XHR the request and on answer change the play-image to the pause-image.

Are there plans to improve this?

Schöne Grüße aus Bremen,
comdoxx

**Comment by MiczFlor** [comment]
Hi @comdoxx 
Grüße aus Berlin nach Bremen :)
The Web UI could need a rethinking. Sure. In the first version, the Phoniebox was without WebUI and everything was done via samba shares and ssh. Then the first version was without ajax. Now there is a lot of ajax and it actually slows the page load down :) meaning: more ajax would be an improvement (while my heart sometimes sighs and wants to go back to no ajax...).
The mpd status needed for dynamic reloading of playout information does slow things down (was it you who noted that in a separate thread?). Not sure what the best way of going forward would be.
Possibly the settings of a page (like toggle resume) should not be on the home page but a folder settings page. I have to think about this.
If you have time on your hands and skills and ideas, I am happy to start working on this. Possibly starting with a "index2.php" page - and then make a switch when it's really working and finished. Because there are quite a few Phonieboxes out there that update with git pull, the ripple effect of unforeseen changes would need to be taken into account.
Thanks for your input. Let's see where this stone will roll now that you tipped it :)
All the best, micz
