### ISSUE TITLE
Alternate PINs when used with I2C - What are the new PINs for standard functions?

### ISSUE THREAD

**Issue by derOger** [MiczFlor/RPi-Jukebox-RFID#459]
Hello,
I have build the buttons for my Phoniebox and wired a LCD-display with I2C. Now the power button doesn't fit. And in the upper table all the standards are missing. So I have wired all after the classic table and they work. But the shutdown-button can't be used. So what have I missed when using this table? Since the new shut down button uses the next PIN in classic.
Regards

**Comment by martinclausen2** [comment]
Shutdown must always be on GPIO 3, since this pin is the only one able to wake up the rpi. Therefor shutdown & power up is in both classic and flexible pinout GPIO 3, which is - as you noted - an alternate function to the I2C bus.
You could try to use bit-banging to generate a software defined I2C to control your LCD. I do not know what the performance penalty would be, I guess you would have to give it a try.
