### ISSUE TITLE
Internetradiostreams do not start

### ISSUE THREAD

**Issue by TM4G1** [MiczFlor/RPi-Jukebox-RFID#49]
Hi MiczFlor,

first of all thanks a ton for this super cool project. I just finished with the set up of the first jukebox, which is for our daughter. Now my wife demands another one for her godchild. :-)

With the second one I got an issue as I cannot playback internet radio streams. Local files work like a charm. Would you have a suggestion how to investigate? I already checked and found out that the latest installation is on version 0.9.4. The previous jukebox I had set up does not have a version ID in the \RPi-Jukebox-RFID\settings folder so it must be an earlier version.

Both jukeboxes run based on the Jessie Guide.

Thanks for your feedback
Tom

**Comment by MiczFlor** [comment]
Hi @TM4G1 
can you send me a sample link to check why there might be a problem? And please, if you fix it without me, please post here how you solved it, because I want to include these small fixes.
If the godchild has a birthday coming up and you are running against the time ;)  you can download older versions as ZIP files here:
https://github.com/MiczFlor/RPi-Jukebox-RFID/releases 
The 0.9.4 version comes with a web app interface to add streams which I thoroughly tested:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/MANUAL.md#registering-a-new-rfid-card-or-key-fob
Hm hm hm, I will try to find some time tonight.

**Comment by TM4G1** [comment]
Hi @MiczFlor,

luckily it is not that urgent ;-) We still plan with more time for building a cool case. See attached screenshot showing the set up. On the right side (ip ending with 46) I installed a version prio to 0.9.4. Here radio stream works fine. On the left side (ip ending with 40) I installed it based on version 0.9.4.

Here the radio stream URL: http://streamtdy.ir-media-tec.com/cool/mp3-128/web/play.m3u 

![radiostreamsetup](https://user-images.githubusercontent.com/39740751/40731624-c0d9b5c6-6431-11e8-8378-2df7ce651465.PNG)

I also tried set up the internet radio stream via web app. Same negative result unfortunately.

Thanks and best regards
Tom

**Comment by TM4G1** [comment]
I think I got now an idea about the problem... I performed a simple ping on the latest raspberry pi and somehow it does not reach the internet anymore, though it is in the same wifi as the other one is. Will investigate on that further.

**Comment by TM4G1** [comment]
Fixed it! Gateway was not set properly by me. This article helped me! :-)

https://raspberrypi.stackexchange.com/questions/14101/connect-network-is-unreachable-on-a-working-connected-wlan0-interface

**Comment by MiczFlor** [comment]
You were offline :) good thing sometimes the most obvious is the solution.
When you are finished, please add your pics to this thread, I am always happy to see new designs:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/5
