### ISSUE TITLE
Connect or create wifi

### ISSUE THREAD

**Issue by elalemanyo** [MiczFlor/RPi-Jukebox-RFID#7]
Hi,
Will be a nice feature if you can set a default wifi setup, and if there is not possible to connect than RPi-Jukebox will create an own wifi.

Maybe we can use something like this: [Connect to WiFi or Create An Encrypted DHCP Enabled Ad-hoc Network as Fallback](http://lcdev.dk/2012/11/18/raspberry-pi-tutorial-connect-to-wifi-or-create-an-encrypted-dhcp-enabled-ad-hoc-network-as-fallback/)

Thanks!

**Comment by MiczFlor** [comment]
Hi @elalemanyo , thanks for your input. 

There is a HOWTO regarding the access point option:
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/master/docs/WLAN-ACCESS-POINT.md

In general the idea of a fallback option is great. I might add that later, it would make the Jukebox more mobile. Either it is online in the home WiFi or, on the road or on the train, you can access it directly as an access point.

Including this as a general option, I would rather not do, because not all WiFi cards support the access point option. The RPi3 does, but I would like the Jukebox code base to be open to older models, too. Out of the box.
