### ISSUE TITLE
hardcoded install-default

### ISSUE THREAD

**Issue by Luegengladiator** [MiczFlor/RPi-Jukebox-RFID#93]
1) Copy the /etc/dhcpcd.conf and /etc/sudoers without creating a backup isn't a good idea.
2) dhcpcd.conf is hardcoded. I think there are more subnets than 192.168.178 (default Fritz.box)
     first there is a git clone. So we can expect we have network. So try "route -n" to find out the correct
     net segment and default gateway?

**Comment by MiczFlor** [comment]
I am closing this ticket, because of the launch of version 1.0 on master. If you have any issues, please try first if they are still happening on the latest version 1.0. If so, open another ticket, please. 

* Use this thread for update issues [if you are running `stretch`](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/138) 

**The version 1.0 has not been tested on `jessie`**

* Read this thread [if you are running `jessie`](https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/137) 

Version 1.0 is a major improvement (which will be full of bugs, for sure :) and I want to thank all the contributors and Phoniebox lovers with their input, pictures, bug fixes and suggestions.
